apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
  - secretKey: root-username
    remoteRef:
      key: everbloom/production/mongodb
      property: root-username
  - secretKey: root-password
    remoteRef:
      key: everbloom/production/mongodb
      property: root-password
  - secretKey: username
    remoteRef:
      key: everbloom/production/mongodb
      property: username
  - secretKey: password
    remoteRef:
      key: everbloom/production/mongodb
      property: password
