apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - statefulset.yaml
  - service.yaml
  - external-secret.yaml

commonLabels:
  app: mongodb
  component: database
