apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
stringData:
  root-username: root
  root-password: placeholder
  username: everbloom_admin
  password: placeholder
