apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-snapshot
  labels:
    app: mongodb
    component: database
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-snapshot
  labels:
    app: mongodb
    component: database
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-snapshot
  labels:
    app: mongodb
    component: database
subjects:
  - kind: ServiceAccount
    name: mongodb-snapshot
roleRef:
  kind: Role
  name: mongodb-snapshot
  apiGroup: rbac.authorization.k8s.io
