apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-public
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: web-public
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-public
spec:
  minReplicas: 2
  maxReplicas: 5

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-public
spec:
  minAvailable: 1
