apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- external-secret.yaml
- pdb.yaml
- hpa.yaml
commonLabels:
  app: api-core
  component: api
images:
- name: api-core
  newName: 361116840324.dkr.ecr.ap-south-2.amazonaws.com/everbloom/api-core
  newTag: fc99927e9283481ef7dc725704d1a001ff49349d
