apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
    component: observability
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
        component: observability
    spec:
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 30
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:2.2
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          runAsUser: 0
          runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: AWS_REGION
          value: "ap-south-2"
        ports:
        - name: http-metrics
          containerPort: 2020
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http-metrics
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http-metrics
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlibcontainerd
          mountPath: /var/lib/containerd
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlibcontainerd
        hostPath:
          path: /var/lib/containerd
      - name: fluent-bit-config
        configMap:
          name: fluent-bit
      - name: tmp
        emptyDir: {}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
