apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
    component: observability
  annotations:
    # Replace with the IRSA role ARN created by Terraform (or attach CloudWatch permissions to the node role).
    eks.amazonaws.com/role-arn: arn:aws:iam::361116840324:role/everbloom-fluent-bit
