apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ../../../apps/api-core/base

replicas:
  - name: api-core
    count: 1

patchesStrategicMerge:
  - patch.yaml

images:
  - name: api-core
    newTag: staging
