apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-admin
  labels:
    app: web-admin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - web-admin.everbloom.com
    secretName: web-admin-tls
  rules:
  - host: web-admin.everbloom.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-admin
            port:
              number: 80
