apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: web-admin-secrets
  labels:
    app: web-admin
spec:
  data:
  - secretKey: api-base-url
    remoteRef:
      key: everbloom/development/web-admin
      property: api-base-url
  - secretKey: socket-url
    remoteRef:
      key: everbloom/development/web-admin
      property: socket-url
