apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ../../../apps/web-admin/base

replicas:
  - name: web-admin
    count: 1

patchesStrategicMerge:
  - patch.yaml
  - configmap-patch.yaml
  - external-secret-patch.yaml
  - hpa-delete.yaml

images:
  - name: 361116840324.dkr.ecr.ap-south-2.amazonaws.com/everbloom/web-admin
    newTag: staging
