/**
 * Analytics Report Generation Service
 * Generates PDF and CSV reports for analytics data
 */

import PDFDocument from 'pdfkit';
import * as projectService from '../project/project.service';
import * as locationService from '../location/location.service';
import * as userAdminService from '../admin/user-admin.service';
import { 
  ReportType, 
  UserRole, 
  ReportGenerationRequest,
  ReportSuggestion,
  ReportMetadata 
} from './analytics-report.types';
import { AppError } from '../../common/exceptions/app-error';
import { brandConfig } from '../../config/brand';
import { createLogger } from '../../infrastructure/logger';

// Use logger factory for non-NestJS context
const logger = createLogger();
import { 
  hasReportPermission,
  getAllowedReportTypes 
} from './analytics-permissions.constants';
import { getAccessDeniedMessage, getMissingRoleMessage } from './analytics-error-messages';
import { getLocationTypeLabel, getMaterialTypeLabel } from '../../types/collections';
import { PdfService, TableColumn } from '../../infrastructure/export/pdf.service';

/**
 * Generate PDF report for analytics data
 */
export const generatePDFReport = async (
  request: ReportGenerationRequest,
  analyticsData: unknown
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const pdfService = new PdfService();
      const doc = new PDFDocument({
        margin: 50,
        size: 'A4',
      });

      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);

      // Compact header - minimized
      doc.fontSize(12)
        .font('Helvetica-Bold')
        .text(brandConfig.name || 'Analytics Report', {
          align: 'center',
        })
        .moveDown(0.1);

      doc.fontSize(14)
        .font('Helvetica-Bold')
        .text(request.options?.reportTitle || `${getReportTypeLabel(request.reportType)} Report`, {
          align: 'center',
        })
        .moveDown(0.2);

      // Compact metadata in two columns - minimized
      const metadataY = doc.y;
      doc.fontSize(8)
        .font('Helvetica')
        .text(`Generated: ${new Date().toLocaleDateString('en-IN', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        })} ${new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}`, 50, metadataY, { width: 250 })
        .text(`Role: ${request.role.charAt(0).toUpperCase() + request.role.slice(1)}`, 300, metadataY, { width: 245, align: 'right' });

      if (request.filters?.startDate || request.filters?.endDate) {
        const startDate = request.filters.startDate 
          ? new Date(request.filters.startDate).toLocaleDateString('en-IN', { month: 'short', day: 'numeric', year: 'numeric' })
          : 'N/A';
        const endDate = request.filters.endDate
          ? new Date(request.filters.endDate).toLocaleDateString('en-IN', { month: 'short', day: 'numeric', year: 'numeric' })
          : 'N/A';
        doc.text(`Period: ${startDate} - ${endDate}`, 50, metadataY + 10, { width: 495 });
      }

      doc.y = metadataY + 20;
      
      // Divider line
      pdfService.addSectionDivider(doc, 0, 0.5);

      // Executive Summary - Consistent section title (left-aligned, compact)
      pdfService.addSectionTitle(doc, 'Executive Summary', 11, 0.15);

      doc.fontSize(8)
        .font('Helvetica')
        .fillColor('#333333')
        .text(generateSummaryText(request.reportType, analyticsData), {
          lineGap: 1.5,
        })
        .fillColor('#000000')
        .moveDown(0.5);
      
      // Ensure consistent font after summary - reset to default
      doc.fontSize(9)
        .font('Helvetica')
        .fillColor('#000000');

      // Detailed sections based on report type
      addReportSections(doc, request.reportType, analyticsData, request.options, pdfService);

      // Footer section with proper page break
      pdfService.addPageBreakIfNeeded(doc, 100);
      pdfService.addSectionDivider(doc, 1, 0.5);

      doc.fontSize(8)
        .font('Helvetica')
        .text('Report Metadata', { underline: true })
        .moveDown(0.2);

      if (request.filters) {
        const filterEntries = Object.entries(request.filters).filter(([, value]) => value);
        if (filterEntries.length > 0) {
          filterEntries.forEach(([key, value]) => {
            const label = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1');
            doc.fontSize(7).text(`${label}: ${value}`);
          });
          doc.moveDown(0.2);
        }
      }

      doc.fontSize(7)
        .text(`Generated by: ${request.userId || 'System'} | Role: ${request.role}`, { align: 'right' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Generate CSV report for analytics data
 */
export const generateCSVReport = async (
  request: ReportGenerationRequest,
  analyticsData: unknown
): Promise<string> => {
  const metadata: ReportMetadata = {
    reportType: request.reportType,
    format: 'csv',
    generatedAt: new Date(),
    generatedBy: request.userId || 'system',
    dateRange: request.filters?.startDate && request.filters?.endDate
      ? {
          startDate: new Date(request.filters.startDate),
          endDate: new Date(request.filters.endDate),
        }
      : undefined,
    filters: request.filters,
  };

  const lines: string[] = [];
  
  // Metadata header
  lines.push('# Analytics Report');
  lines.push(`# Report Type: ${getReportTypeLabel(request.reportType)}`);
  lines.push(`# Generated: ${metadata.generatedAt.toISOString()}`);
  lines.push(`# Generated By: ${metadata.generatedBy}`);
  lines.push(`# Role: ${request.role}`);
  
  if (metadata.dateRange) {
    lines.push(`# Date Range: ${metadata.dateRange.startDate?.toISOString()} to ${metadata.dateRange.endDate?.toISOString()}`);
  }
  
  lines.push('#');
  lines.push('');

  // Data rows
  const csvData = convertAnalyticsDataToCSV(request.reportType, analyticsData);
  if (csvData.length > 0) {
    // Headers
    const headers = Object.keys(csvData[0]);
    lines.push(headers.join(','));

    // Data rows
    csvData.forEach(row => {
      const values = headers.map(header => {
        const value = row[header];
        if (value === null || value === undefined) return '';
        const stringValue = String(value);
        return stringValue.includes(',') ? `"${stringValue}"` : stringValue;
      });
      lines.push(values.join(','));
    });
  }

  return lines.join('\n');
};

/**
 * Get report suggestions based on role and current data
 */
export const getReportSuggestions = async (
  _userId: string,
  role: UserRole,
  currentFilters?: {
    startDate?: string;
    endDate?: string;
    reportType?: ReportType;
  }
): Promise<ReportSuggestion[]> => {
  const suggestions: ReportSuggestion[] = [];

  // Get allowed report types for this role
  const allowedReportTypes = getAllowedReportTypes(role);
  if (!allowedReportTypes || allowedReportTypes.length === 0) {
    return []; // Return empty if role has no permissions
  }

  // Get default report type based on role (first allowed type)
  const getDefaultReportType = (): ReportType => {
    if (currentFilters?.reportType && hasReportPermission(role, currentFilters.reportType)) {
      return currentFilters.reportType;
    }
    return allowedReportTypes[0]; // Use first allowed type as default
  };

  const defaultReportType = getDefaultReportType();

  // Time-based suggestions
  if (currentFilters?.startDate && currentFilters?.endDate) {
    const startDate = new Date(currentFilters.startDate);
    const endDate = new Date(currentFilters.endDate);
    const daysDiff = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));

    if (daysDiff >= 28 && daysDiff <= 31) {
      suggestions.push({
        id: 'monthly-report',
        title: 'Monthly Report',
        description: 'Generate a comprehensive monthly report',
        reportType: defaultReportType,
        format: 'pdf',
        suggestedFilters: currentFilters,
        priority: 'high',
        reason: 'Current view shows monthly data',
      });
    } else if (daysDiff >= 88 && daysDiff <= 93) {
      suggestions.push({
        id: 'quarterly-report',
        title: 'Quarterly Report',
        description: 'Generate a quarterly summary report',
        reportType: defaultReportType,
        format: 'pdf',
        suggestedFilters: currentFilters,
        priority: 'high',
        reason: 'Current view shows quarterly data',
      });
    } else if (daysDiff >= 360 && daysDiff <= 370) {
      suggestions.push({
        id: 'yearly-report',
        title: 'Yearly Summary Report',
        description: 'Generate an annual summary report',
        reportType: defaultReportType,
        format: 'pdf',
        suggestedFilters: currentFilters,
        priority: 'high',
        reason: 'Current view shows yearly data',
      });
    }
  }

  // Role-specific suggestions
  if (role === 'user') {
    suggestions.push({
      id: 'personal-summary',
      title: 'Personal Performance Summary',
      description: 'Generate your personal performance report',
      reportType: 'my-analytics',
      format: 'pdf',
      priority: 'medium',
      reason: 'Recommended for tracking personal progress',
    });
  } else if (role === 'agent') {
    suggestions.push({
      id: 'agent-performance',
      title: 'Performance Review Report',
      description: 'Generate your performance review report',
      reportType: 'my-analytics',
      format: 'pdf',
      priority: 'high',
      reason: 'Useful for performance reviews',
    });

    suggestions.push({
      id: 'location-performance',
      title: 'Location Performance Report',
      description: 'Generate report for your top performing locations',
      reportType: 'location',
      format: 'pdf',
      priority: 'medium',
      reason: 'Helps identify best performing locations',
    });
  } else if (role === 'admin' || role === 'super_admin') {
    suggestions.push({
      id: 'team-performance',
      title: 'Team Performance Report',
      description: 'Generate comprehensive team performance report',
      reportType: 'agent',
      format: 'pdf',
      priority: 'high',
      reason: 'Essential for team management',
    });

    suggestions.push({
      id: 'financial-summary',
      title: 'Financial Summary Report',
      description: 'Generate financial analytics report',
      reportType: 'collection',
      format: 'pdf',
      priority: 'high',
      reason: 'Important for financial planning',
    });

    suggestions.push({
      id: 'comprehensive-report',
      title: 'Comprehensive Analytics Report',
      description: 'Generate complete analytics report with all metrics',
      reportType: 'comprehensive',
      format: 'pdf',
      priority: 'medium',
      reason: 'Complete overview of all analytics',
    });
  }

  // Data export suggestions
  suggestions.push({
    id: 'data-export',
    title: 'Export Data to CSV',
    description: 'Export current analytics data for further analysis',
    reportType: defaultReportType,
    format: 'csv',
    suggestedFilters: currentFilters,
    priority: 'low',
    reason: 'Useful for external analysis',
  });

  // Filter suggestions to only include report types the user has permission for
  const filteredSuggestions = suggestions.filter(suggestion => 
    hasReportPermission(role, suggestion.reportType)
  );

  return filteredSuggestions.sort((a, b) => {
    const priorityOrder = { high: 0, medium: 1, low: 2 };
    return priorityOrder[a.priority] - priorityOrder[b.priority];
  });
};

/**
 * Validate user has access to report type
 */
const validateReportAccess = (reportType: ReportType, userRole: UserRole): void => {
  const allowedTypes = getAllowedReportTypes(userRole);
  if (!allowedTypes || allowedTypes.length === 0) {
    throw new AppError(getMissingRoleMessage(), 400);
  }

  if (!hasReportPermission(userRole, reportType)) {
    const errorMessage = getAccessDeniedMessage(userRole, reportType, 'generate');
    throw new AppError(errorMessage, 403);
  }
};

/**
 * Generate report based on request
 */
export const generateReport = async (
  request: ReportGenerationRequest
): Promise<Buffer | string> => {
  try {
    // Log the report type being generated for debugging
    logger.debug(`Generating ${request.reportType} report for user ${request.userId} with role ${request.role}`);

    // Validate user has access to this report type (additional check in service layer)
    validateReportAccess(request.reportType, request.role);

    // Fetch analytics data based on report type
    const analyticsData = await fetchAnalyticsData(request);

    // Validate that data was fetched successfully
    if (!analyticsData) {
      throw new AppError(`No data available for ${request.reportType} report`, 404);
    }

    logger.debug(`Successfully fetched data for ${request.reportType} report`);

    if (request.format === 'pdf') {
      return generatePDFReport(request, analyticsData);
    } else {
      return generateCSVReport(request, analyticsData);
    }
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(`Failed to generate ${request.reportType} report: ${error instanceof Error ? error.message : 'Unknown error'}`, 500);
  }
};

/**
 * Fetch analytics data based on report type
 */
const fetchAnalyticsData = async (
  request: ReportGenerationRequest
): Promise<unknown> => {
  // Convert date strings to Date objects, handling empty strings
  const filters = {
    startDate: request.filters?.startDate && request.filters.startDate.trim() 
      ? new Date(request.filters.startDate) 
      : undefined,
    endDate: request.filters?.endDate && request.filters.endDate.trim() 
      ? new Date(request.filters.endDate) 
      : undefined,
  };

  logger.debug(`Fetching analytics data for report type: ${request.reportType}`, {
    filters: {
      startDate: filters.startDate?.toISOString(),
      endDate: filters.endDate?.toISOString(),
      rawStartDate: request.filters?.startDate,
      rawEndDate: request.filters?.endDate,
    },
  });

  switch (request.reportType) {
    case 'my-analytics':
      if (!request.userId) {
        throw new AppError('User ID required for my-analytics report', 400);
      }
      return projectService.getMyCollectionAnalytics(request.userId, filters);

    case 'location':
      return locationService.getLocationAnalytics({
        ...filters,
        locationType: request.filters?.locationType,
        userId: request.userId,
        userRole: request.role,
      });

    case 'agent':
      try {
        const agentData = await projectService.getAgentPerformanceAnalytics(filters);
        // Ensure the data structure is correct
        if (!agentData || typeof agentData !== 'object') {
          throw new AppError('Invalid agent analytics data structure', 500);
        }
        // Ensure agents array exists
        if (!Array.isArray((agentData as { agents?: unknown }).agents)) {
          return {
            agents: [],
            leaderboard: {
              byCollections: [],
              byRevenue: [],
              byWeight: [],
            },
            teamAverages: {
              averageCollections: 0,
              averageRevenue: 0,
              averageWeight: 0,
              averageCollectionsPerDay: 0,
              averageCollectionValue: 0,
            },
          };
        }
        return agentData;
      } catch (error) {
        logger.error('Error fetching agent analytics:', error);
        throw new AppError(`Failed to fetch agent analytics: ${error instanceof Error ? error.message : 'Unknown error'}`, 500);
      }

    case 'collection':
      return projectService.getCollectionAnalytics({
        ...filters,
        userId: request.userId,
        userRole: request.role,
      });

    case 'user':
      return userAdminService.getUserStats(request.role);

    case 'comprehensive': {
      // Fetch all analytics for comprehensive report
      const [location, agent, collection, user] = await Promise.all([
        locationService.getLocationAnalytics({
          ...filters,
          locationType: request.filters?.locationType,
          userId: request.userId,
          userRole: request.role,
        }),
        projectService.getAgentPerformanceAnalytics(filters),
        projectService.getCollectionAnalytics({
          ...filters,
          userId: request.userId,
          userRole: request.role,
        }),
        userAdminService.getUserStats(request.role),
      ]);
      return { location, agent, collection, user };
    }

    default:
      throw new AppError(`Unknown report type: ${request.reportType}`, 400);
  }
};

/**
 * Helper functions
 */
const getReportTypeLabel = (reportType: ReportType): string => {
  const labels: Record<ReportType, string> = {
    'my-analytics': 'My Analytics',
    'location': 'Location Analytics',
    'agent': 'Agent Analytics',
    'collection': 'Collection Analytics',
    'user': 'User Analytics',
    'comprehensive': 'Comprehensive Analytics',
  };
  return labels[reportType] || reportType;
};

const generateSummaryText = (reportType: ReportType, data: unknown): string => {
  if (!data || typeof data !== 'object') {
    return `This report contains analytics data for ${getReportTypeLabel(reportType)}.`;
  }

  const dataObj = data as Record<string, unknown>;

  switch (reportType) {
    case 'my-analytics': {
      const myOverview = (dataObj.overview as { totalCollections?: number; totalRevenue?: number; totalWeight?: number }) || {};
      return `Personal Performance Summary:
- Total Collections: ${myOverview.totalCollections || 0}
- Total Revenue: ₹${(myOverview.totalRevenue || 0).toLocaleString('en-IN')}
- Total Weight: ${(myOverview.totalWeight || 0).toFixed(2)} kg`;
    }

    case 'location': {
      const locData = dataObj as { 
        total?: number; 
        active?: number; 
        inactive?: number;
        totalUsage?: number; 
        averageUsage?: number;
        byType?: Record<string, number>;
        mostUsed?: Array<{ locationName: string; usageCount: number }>;
      };
      const byTypeCount = locData.byType ? Object.keys(locData.byType).length : 0;
      const topLocation = locData.mostUsed && locData.mostUsed.length > 0 
        ? locData.mostUsed[0].locationName 
        : 'N/A';
      return `Location Analytics Summary:
- Total Locations: ${locData.total || 0}
- Active Locations: ${locData.active || 0}
- Inactive Locations: ${locData.inactive || 0}
- Total Usage: ${locData.totalUsage || 0}
- Average Usage: ${((locData.averageUsage || 0)).toFixed(2)}
- Location Types: ${byTypeCount}
- Most Used Location: ${topLocation}`;
    }

    case 'agent': {
      const agentData = dataObj as { 
        agents?: Array<{ totalCollections?: number; totalRevenue?: number; agentName?: string }>; 
        teamAverages?: { averageCollections?: number; averageRevenue?: number; averageWeight?: number } 
      };
      const agentCount = Array.isArray(agentData.agents) ? agentData.agents.length : 0;
      const totalCollections = agentData.agents?.reduce((sum, agent) => sum + (agent.totalCollections || 0), 0) || 0;
      const totalRevenue = agentData.agents?.reduce((sum, agent) => sum + (agent.totalRevenue || 0), 0) || 0;
      const avgCollections = agentData.teamAverages?.averageCollections || 0;
      const topAgent = agentData.agents && agentData.agents.length > 0
        ? agentData.agents.reduce((top, agent) => 
            (agent.totalCollections || 0) > (top.totalCollections || 0) ? agent : top, 
            agentData.agents[0]
          )
        : null;
      return `Agent Performance Summary:
- Total Agents: ${agentCount}
- Total Collections: ${totalCollections}
- Total Revenue: ₹${totalRevenue.toLocaleString('en-IN')}
- Average Collections per Agent: ${avgCollections.toFixed(1)}
${topAgent ? `- Top Performer: ${topAgent.agentName || 'N/A'}` : ''}`;
    }

    case 'collection': {
      const collData = dataObj as { 
        totalRecycled?: number; 
        totalPickups?: number;
        byMaterialType?: Array<{ materialType: string; count: number; totalWeight: number }>;
      };
      const avgPerPickup = collData.totalPickups && collData.totalPickups > 0
        ? ((collData.totalRecycled || 0) / collData.totalPickups).toFixed(2)
        : '0.00';
      const materialTypeCount = collData.byMaterialType ? collData.byMaterialType.length : 0;
      return `Collection Analytics Summary:
- Total Recycled: ${(collData.totalRecycled || 0).toFixed(2)} kg
- Total Pickups: ${collData.totalPickups || 0}
- Average per Pickup: ${avgPerPickup} kg
- Material Types: ${materialTypeCount}`;
    }

    case 'user': {
      const userData = dataObj as { 
        total?: number; 
        active?: number; 
        inactive?: number;
        recent?: number;
      };
      const totalUsers = userData.total || 0;
      const activeUsers = userData.active || 0;
      const activationRate = totalUsers > 0 ? ((activeUsers / totalUsers) * 100).toFixed(1) : '0.0';
      return `User Analytics Summary:
- Total Users: ${totalUsers}
- Active Users: ${activeUsers}
- Inactive Users: ${userData.inactive || 0}
- Activation Rate: ${activationRate}%
- Recent Users (7 days): ${userData.recent || 0}`;
    }

    case 'comprehensive': {
      const comprehensiveData = dataObj as {
        location?: { total?: number; active?: number; totalUsage?: number };
        agent?: { agents?: Array<unknown>; teamAverages?: { averageCollections?: number } };
        collection?: { totalRecycled?: number; totalPickups?: number };
        user?: { total?: number; active?: number; inactive?: number };
      };
      
      const locationSummary = comprehensiveData.location
        ? `Locations: ${comprehensiveData.location.total || 0} total, ${comprehensiveData.location.active || 0} active`
        : '';
      const agentSummary = comprehensiveData.agent
        ? `Agents: ${Array.isArray(comprehensiveData.agent.agents) ? comprehensiveData.agent.agents.length : 0} total`
        : '';
      const collectionSummary = comprehensiveData.collection
        ? `Collections: ${(comprehensiveData.collection.totalRecycled || 0).toFixed(2)} kg recycled, ${comprehensiveData.collection.totalPickups || 0} pickups`
        : '';
      const userSummary = comprehensiveData.user
        ? `Users: ${comprehensiveData.user.total || 0} total, ${comprehensiveData.user.active || 0} active`
        : '';
      
      return `Comprehensive Analytics Summary:
${locationSummary ? `- ${locationSummary}\n` : ''}${agentSummary ? `- ${agentSummary}\n` : ''}${collectionSummary ? `- ${collectionSummary}\n` : ''}${userSummary ? `- ${userSummary}` : ''}`;
    }

    default:
      return `This report contains analytics data for ${getReportTypeLabel(reportType)}.`;
  }
};

const addReportSections = (
  doc: InstanceType<typeof PDFDocument>,
  reportType: ReportType,
  data: unknown,
  options: { includeCharts?: boolean; includeDetailedData?: boolean } | undefined,
  pdfService: PdfService
): void => {
  if (!data || typeof data !== 'object') {
    doc.fontSize(9).text('No data available for this report.');
    return;
  }

  const dataObj = data as Record<string, unknown>;

  // Key Metrics Section - Consistent section title (left-aligned, compact)
  pdfService.addSectionTitle(doc, 'Key Metrics', 11, 0.2, 'left');

  // Ensure consistent font settings (compact)
  doc.fontSize(8)
    .font('Helvetica')
    .fillColor('#333333');

  switch (reportType) {
    case 'my-analytics': {
      // Improved metrics display with better formatting
      const myMetricsY = doc.y;
      const myOverview = (dataObj.overview as Record<string, unknown>) || {};
      
      // Metrics boxes - more compact
      const metricsBoxHeight = 28;
      const metricsBoxWidth = 115;
      const metricsGap = 8;
      const metricsStartX = 50;
      
      // Collections box
      doc.rect(metricsStartX, myMetricsY, metricsBoxWidth, metricsBoxHeight)
        .fillColor('#f0f7ff')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0e0f0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Collections', metricsStartX + 5, myMetricsY + 3, { width: metricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(myOverview.totalCollections || 0), metricsStartX + 5, myMetricsY + 14, { width: metricsBoxWidth - 10 });
      
      // Receipts box
      const receiptsX = metricsStartX + metricsBoxWidth + metricsGap;
      doc.rect(receiptsX, myMetricsY, metricsBoxWidth, metricsBoxHeight)
        .fillColor('#f0fff0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Receipts', receiptsX + 5, myMetricsY + 3, { width: metricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(myOverview.totalReceipts || 0), receiptsX + 5, myMetricsY + 14, { width: metricsBoxWidth - 10 });
      
      // Weight box
      const weightX = receiptsX + metricsBoxWidth + metricsGap;
      doc.rect(weightX, myMetricsY, metricsBoxWidth, metricsBoxHeight)
        .fillColor('#fff8f0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#f0e0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Weight (kg)', weightX + 5, myMetricsY + 3, { width: metricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(((myOverview.totalWeight as number) || 0).toFixed(2), weightX + 5, myMetricsY + 14, { width: metricsBoxWidth - 10 });
      
      // Revenue box
      const revenueX = weightX + metricsBoxWidth + metricsGap;
      doc.rect(revenueX, myMetricsY, metricsBoxWidth, metricsBoxHeight)
        .fillColor('#f0fff8')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0e8')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Revenue', revenueX + 5, myMetricsY + 3, { width: metricsBoxWidth - 10 });
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#000000')
        .text(`₹${((myOverview.totalAmount as number) || 0).toLocaleString('en-IN')}`, revenueX + 5, myMetricsY + 14, { width: metricsBoxWidth - 10 });
      
      doc.y = myMetricsY + metricsBoxHeight + 8;
      doc.fillColor('#000000');
      doc.moveDown(0.3);

      if (options?.includeDetailedData) {
        // Material Type Breakdown - Using table for better presentation with large datasets
        const byMaterialType = (dataObj.byMaterialType as Array<{ materialType: string; count: number; totalWeight: number }>) || [];
        if (byMaterialType.length > 0) {
          pdfService.addSectionTitle(doc, 'Material Type Breakdown', 10, 0.3, 'left');

          const materialColumns: TableColumn[] = [
            { header: 'Material Type', width: 200, align: 'left' },
            { header: 'Count', width: 80, align: 'right' },
            { header: 'Total Weight (kg)', width: 120, align: 'right', formatter: pdfService.formatNumber(2) },
            { header: 'Avg Weight (kg)', width: 95, align: 'right', formatter: pdfService.formatNumber(2) },
          ];

          const materialTableData = byMaterialType.map(item => {
            const materialLabel = getMaterialTypeLabel(item.materialType || 'Unknown');
            const avgWeight = item.count > 0 ? item.totalWeight / item.count : 0;
            return [
              materialLabel,
              item.count,
              item.totalWeight,
              avgWeight,
            ];
          });

          pdfService.createTable(doc, materialColumns, materialTableData, {
            startX: 50,
            rowHeight: 16,
            fontSize: 8,
            headerFontSize: 9,
            showAlternateRows: true,
            maxRowsPerPage: 35,
            repeatHeaderOnNewPage: true,
          });

          doc.moveDown(0.5);
        }

        // Location Type Breakdown - Using table
        const byLocationType = (dataObj.byLocationType as Array<{ locationType: string; count: number }>) || [];
        if (byLocationType.length > 0) {
          pdfService.addSectionTitle(doc, 'Location Type Breakdown', 10, 0.3, 'left');

          const locationColumns: TableColumn[] = [
            { header: 'Location Type', width: 300, align: 'left' },
            { header: 'Count', width: 195, align: 'right' },
          ];

          const locationTableData = byLocationType.map(item => [
            getLocationTypeLabel(item.locationType || 'Unknown'),
            item.count,
          ]);

          pdfService.createTable(doc, locationColumns, locationTableData, {
            startX: 50,
            rowHeight: 16,
            fontSize: 8,
            headerFontSize: 9,
            showAlternateRows: true,
            maxRowsPerPage: 35,
            repeatHeaderOnNewPage: true,
          });

          doc.moveDown(0.5);
        }
      }
      break;
    }

    case 'location': {
      // Improved metrics display with boxes - Compact
      const locationMetricsY = doc.y;
      const locationTotal = (dataObj.total as number) || 0;
      const locationActive = (dataObj.active as number) || 0;
      const locationInactive = (dataObj.inactive as number) || 0;
      const locationUsage = (dataObj.totalUsage as number) || 0;
      const locationAvgUsage = ((dataObj.averageUsage as number) || 0).toFixed(2);
      
      const locMetricsBoxHeight = 28;
      const locMetricsBoxWidth = 110;
      const locMetricsGap = 8;
      const locMetricsStartX = 50;
      
      // Total box
      doc.rect(locMetricsStartX, locationMetricsY, locMetricsBoxWidth, locMetricsBoxHeight)
        .fillColor('#f0f7ff')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0e0f0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Total', locMetricsStartX + 5, locationMetricsY + 3, { width: locMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(locationTotal), locMetricsStartX + 5, locationMetricsY + 14, { width: locMetricsBoxWidth - 10 });
      
      // Active box
      const activeX = locMetricsStartX + locMetricsBoxWidth + locMetricsGap;
      doc.rect(activeX, locationMetricsY, locMetricsBoxWidth, locMetricsBoxHeight)
        .fillColor('#f0fff0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Active', activeX + 5, locationMetricsY + 3, { width: locMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(locationActive), activeX + 5, locationMetricsY + 14, { width: locMetricsBoxWidth - 10 });
      
      // Inactive box
      const inactiveX = activeX + locMetricsBoxWidth + locMetricsGap;
      doc.rect(inactiveX, locationMetricsY, locMetricsBoxWidth, locMetricsBoxHeight)
        .fillColor('#fff8f0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#f0e0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Inactive', inactiveX + 5, locationMetricsY + 3, { width: locMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(locationInactive), inactiveX + 5, locationMetricsY + 14, { width: locMetricsBoxWidth - 10 });
      
      // Usage box
      const usageX = inactiveX + locMetricsBoxWidth + locMetricsGap;
      doc.rect(usageX, locationMetricsY, locMetricsBoxWidth, locMetricsBoxHeight)
        .fillColor('#f0fff8')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0e8')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Usage', usageX + 5, locationMetricsY + 3, { width: locMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(locationUsage), usageX + 5, locationMetricsY + 14, { width: locMetricsBoxWidth - 10 });
      
      // Avg Usage below - Compact
      doc.fontSize(8).font('Helvetica').fillColor('#333333')
        .text(`Average Usage: ${locationAvgUsage}`, locMetricsStartX, locationMetricsY + locMetricsBoxHeight + 6, { width: 495 });
      
      doc.y = locationMetricsY + locMetricsBoxHeight + 20;
      doc.fillColor('#000000');
      doc.moveDown(0.3);

      if (options?.includeDetailedData) {
        // Location Type Breakdown - Using table with null handling
        const byType = (dataObj.byType as Record<string, number>) || {};
        const typeEntries = Object.entries(byType)
          .filter(([, count]) => count != null && count > 0)
          .map(([type, count]) => {
            const normalizedType = (type === null || type === undefined || type === '' || type === 'null') 
              ? 'Unknown' 
              : type;
            return [normalizedType, count] as [string, number];
          });
        
        if (typeEntries.length > 0) {
          pdfService.addSectionTitle(doc, 'Location Type Breakdown', 10, 0.3, 'left');

          const locationTypeColumns: TableColumn[] = [
            { header: 'Location Type', width: 350, align: 'left' },
            { header: 'Count', width: 145, align: 'right' },
          ];

          const locationTypeTableData = typeEntries.map(([type, count]) => [
            type === 'Unknown' ? 'Unknown/Not Specified' : getLocationTypeLabel(type),
            count,
          ]);

          pdfService.createTable(doc, locationTypeColumns, locationTypeTableData, {
            startX: 50,
            rowHeight: 16,
            fontSize: 8,
            headerFontSize: 9,
            showAlternateRows: true,
            maxRowsPerPage: 35,
            repeatHeaderOnNewPage: true,
          });

          doc.moveDown(0.5);
        }

        // Most Used Locations - Using table
        const mostUsed = (dataObj.mostUsed as Array<{ locationName: string; usageCount: number }>) || [];
        if (mostUsed.length > 0) {
          pdfService.addSectionTitle(doc, 'Top Locations', 10, 0.3, 'left');

          const topLocationsColumns: TableColumn[] = [
            { header: 'Rank', width: 50, align: 'center' },
            { header: 'Location Name', width: 345, align: 'left' },
            { header: 'Usage Count', width: 100, align: 'right' },
          ];

          const topLocationsTableData = mostUsed.map((loc, index) => [
            index + 1,
            loc.locationName,
            loc.usageCount,
          ]);

          pdfService.createTable(doc, topLocationsColumns, topLocationsTableData, {
            startX: 50,
            rowHeight: 16,
            fontSize: 8,
            headerFontSize: 9,
            showAlternateRows: true,
            maxRowsPerPage: 35,
            repeatHeaderOnNewPage: true,
          });

          doc.moveDown(0.5);
        }

        // Usage Trends Summary - Compact
        const usageTrends = (dataObj.usageTrends as Array<{ date: string; count: number }>) || [];
        if (usageTrends.length > 0) {
          pdfService.addSectionTitle(doc, 'Usage Trends Summary', 10, 0.2, 'left');
          doc.fontSize(8)
            .font('Helvetica')
            .fillColor('#333333');
          const totalCollections = usageTrends.reduce((sum, trend) => sum + (trend.count || 0), 0);
          const avgPerDay = usageTrends.length > 0 ? totalCollections / usageTrends.length : 0;
          const maxDay = usageTrends.reduce((max, trend) => 
            (trend.count || 0) > (max.count || 0) ? trend : max, 
            { date: '', count: 0 }
          );
          doc.text(`Total: ${totalCollections} | Avg/Day: ${avgPerDay.toFixed(1)} | Peak: ${new Date(maxDay.date).toLocaleDateString('en-IN', { month: 'short', day: 'numeric' })} (${maxDay.count})`, { width: 495 });
          doc.fillColor('#000000');
          doc.moveDown(0.3);
        }

        // By City Breakdown - Using table
        const byCity = (dataObj.byCity as Array<{ city: string; count: number }>) || [];
        if (byCity.length > 0) {
          pdfService.addSectionTitle(doc, 'Top Cities', 10, 0.3, 'left');

          const cityColumns: TableColumn[] = [
            { header: 'Rank', width: 50, align: 'center' },
            { header: 'City', width: 345, align: 'left' },
            { header: 'Count', width: 100, align: 'right' },
          ];

          const cityTableData = byCity.map((item, index) => [
            index + 1,
            item.city || 'Unknown',
            item.count,
          ]);

          pdfService.createTable(doc, cityColumns, cityTableData, {
            startX: 50,
            rowHeight: 16,
            fontSize: 8,
            headerFontSize: 9,
            showAlternateRows: true,
            maxRowsPerPage: 35,
            repeatHeaderOnNewPage: true,
          });

          doc.moveDown(0.5);
        }
      }
      break;
    }

    case 'agent': {
      // Improved metrics display with boxes - Compact
      const agentMetricsY = doc.y;
      const agents = (dataObj.agents as Array<Record<string, unknown>>) || [];
      const teamAverages = (dataObj.teamAverages as { averageCollections?: number; averageRevenue?: number; averageWeight?: number; averageCollectionsPerDay?: number; averageCollectionValue?: number }) || {};
      
      const totalCollections = agents.reduce((sum, agent) => sum + ((agent.totalCollections as number) || 0), 0);
      const totalRevenue = agents.reduce((sum, agent) => sum + ((agent.totalRevenue as number) || 0), 0);
      const avgPerDay = teamAverages.averageCollectionsPerDay?.toFixed(2) || '0.00';
      
      const agentMetricsBoxHeight = 28;
      const agentMetricsBoxWidth = 110;
      const agentMetricsGap = 8;
      const agentMetricsStartX = 50;
      
      // Agents count box
      doc.rect(agentMetricsStartX, agentMetricsY, agentMetricsBoxWidth, agentMetricsBoxHeight)
        .fillColor('#f0f7ff')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0e0f0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Agents', agentMetricsStartX + 5, agentMetricsY + 3, { width: agentMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(agents.length), agentMetricsStartX + 5, agentMetricsY + 14, { width: agentMetricsBoxWidth - 10 });
      
      // Collections box
      const collectionsX = agentMetricsStartX + agentMetricsBoxWidth + agentMetricsGap;
      doc.rect(collectionsX, agentMetricsY, agentMetricsBoxWidth, agentMetricsBoxHeight)
        .fillColor('#f0fff0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Collections', collectionsX + 5, agentMetricsY + 3, { width: agentMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(totalCollections), collectionsX + 5, agentMetricsY + 14, { width: agentMetricsBoxWidth - 10 });
      
      // Revenue box
      const revenueX = collectionsX + agentMetricsBoxWidth + agentMetricsGap;
      doc.rect(revenueX, agentMetricsY, agentMetricsBoxWidth, agentMetricsBoxHeight)
        .fillColor('#fff8f0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#f0e0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Revenue', revenueX + 5, agentMetricsY + 3, { width: agentMetricsBoxWidth - 10 });
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#000000')
        .text(`₹${totalRevenue.toLocaleString('en-IN')}`, revenueX + 5, agentMetricsY + 14, { width: agentMetricsBoxWidth - 10 });
      
      // Avg/Day box
      const avgDayX = revenueX + agentMetricsBoxWidth + agentMetricsGap;
      doc.rect(avgDayX, agentMetricsY, agentMetricsBoxWidth, agentMetricsBoxHeight)
        .fillColor('#f0fff8')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0e8')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Avg/Day', avgDayX + 5, agentMetricsY + 3, { width: agentMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(avgPerDay, avgDayX + 5, agentMetricsY + 14, { width: agentMetricsBoxWidth - 10 });
      
      // Additional averages below - Compact
      if (teamAverages.averageCollections !== undefined) {
        doc.fontSize(8).font('Helvetica').fillColor('#333333')
          .text(`Avg Collections: ${teamAverages.averageCollections.toFixed(1)} | Avg Revenue: ₹${((teamAverages.averageRevenue || 0)).toLocaleString('en-IN')} | Avg Weight: ${((teamAverages.averageWeight || 0)).toFixed(2)} kg`, 
            agentMetricsStartX, agentMetricsY + agentMetricsBoxHeight + 6, { width: 495 });
        doc.y = agentMetricsY + agentMetricsBoxHeight + 20;
      } else {
        doc.y = agentMetricsY + agentMetricsBoxHeight + 12;
      }
      doc.fillColor('#000000');
      doc.moveDown(0.3);
      
      if (agents.length === 0) {
        doc.fontSize(10)
          .fillColor('#666666')
          .text('No agent data available for the selected period.');
      } else if (options?.includeDetailedData) {
        // Agent Performance Table - using reusable table utility
        doc.fontSize(12)
          .font('Helvetica-Bold')
          .text('Agent Performance Details')
          .moveDown(0.5);

        const columns: TableColumn[] = [
          { header: 'Rank', width: 40, align: 'center' },
          { header: 'Agent Name', width: 140, align: 'left' },
          { header: 'Collections', width: 75, align: 'right' },
          { header: 'Revenue', width: 95, align: 'right', formatter: pdfService.formatCurrency },
          { header: 'Weight (kg)', width: 80, align: 'right', formatter: pdfService.formatNumber(2) },
          { header: 'Avg/Day', width: 65, align: 'right', formatter: pdfService.formatNumber(2) },
        ];

        const tableData = agents.map((agent, index) => [
          index + 1,
          (agent.agentName as string) || 'Unknown',
          (agent.totalCollections as number) || 0,
          (agent.totalRevenue as number) || 0,
          (agent.totalWeight as number) || 0,
          (agent.collectionsPerDay as number) || 0,
        ]);

        pdfService.createTable(doc, columns, tableData, {
          startX: 50,
          rowHeight: 16,
          fontSize: 8,
          headerFontSize: 9,
          showAlternateRows: true,
          maxRowsPerPage: 35, // Handle large datasets with pagination
          repeatHeaderOnNewPage: true,
        });

        doc.moveDown(0.5);
      }
      break;
    }

    case 'collection': {
      // Improved metrics display with boxes - Compact
      const collMetricsY = doc.y;
      const totalPickups = (dataObj.totalPickups as number) || 0;
      const totalRecycled = (dataObj.totalRecycled as number) || 0;
      const avgPerPickup = totalPickups > 0 ? (totalRecycled / totalPickups).toFixed(2) : '0.00';
      
      const collMetricsBoxHeight = 28;
      const collMetricsBoxWidth = 155;
      const collMetricsGap = 8;
      const collMetricsStartX = 50;
      
      // Recycled box
      doc.rect(collMetricsStartX, collMetricsY, collMetricsBoxWidth, collMetricsBoxHeight)
        .fillColor('#f0f7ff')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0e0f0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Recycled (kg)', collMetricsStartX + 5, collMetricsY + 3, { width: collMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(totalRecycled.toFixed(2), collMetricsStartX + 5, collMetricsY + 14, { width: collMetricsBoxWidth - 10 });
      
      // Pickups box
      const pickupsX = collMetricsStartX + collMetricsBoxWidth + collMetricsGap;
      doc.rect(pickupsX, collMetricsY, collMetricsBoxWidth, collMetricsBoxHeight)
        .fillColor('#f0fff0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Pickups', pickupsX + 5, collMetricsY + 3, { width: collMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(totalPickups), pickupsX + 5, collMetricsY + 14, { width: collMetricsBoxWidth - 10 });
      
      // Avg/Pickup box
      const avgPickupX = pickupsX + collMetricsBoxWidth + collMetricsGap;
      doc.rect(avgPickupX, collMetricsY, collMetricsBoxWidth, collMetricsBoxHeight)
        .fillColor('#fff8f0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#f0e0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Avg/Pickup (kg)', avgPickupX + 5, collMetricsY + 3, { width: collMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(avgPerPickup, avgPickupX + 5, collMetricsY + 14, { width: collMetricsBoxWidth - 10 });
      
      doc.y = collMetricsY + collMetricsBoxHeight + 12;
      doc.fillColor('#000000');
      doc.moveDown(0.3);

      if (options?.includeDetailedData) {
        // Material Type Breakdown - Using table
        const byMaterialType = (dataObj.byMaterialType as Array<{ materialType: string; count: number; totalWeight: number }>) || [];
        if (byMaterialType.length > 0) {
          pdfService.addSectionTitle(doc, 'Material Type Breakdown', 10, 0.3, 'left');

          const collectionMaterialColumns: TableColumn[] = [
            { header: 'Material Type', width: 200, align: 'left' },
            { header: 'Count', width: 80, align: 'right' },
            { header: 'Total Weight (kg)', width: 120, align: 'right', formatter: pdfService.formatNumber(2) },
            { header: 'Avg Weight (kg)', width: 95, align: 'right', formatter: pdfService.formatNumber(2) },
          ];

          const collectionMaterialTableData = byMaterialType.map(item => {
            const materialLabel = getMaterialTypeLabel(item.materialType || 'Unknown');
            const avgWeight = item.count > 0 ? item.totalWeight / item.count : 0;
            return [
              materialLabel,
              item.count,
              item.totalWeight,
              avgWeight,
            ];
          });

          pdfService.createTable(doc, collectionMaterialColumns, collectionMaterialTableData, {
            startX: 50,
            rowHeight: 16,
            fontSize: 8,
            headerFontSize: 9,
            showAlternateRows: true,
            maxRowsPerPage: 35,
            repeatHeaderOnNewPage: true,
          });

          doc.moveDown(0.5);
        }
      }
      break;
    }

    case 'user': {
      // Improved metrics display with boxes - Compact
      const userMetricsY = doc.y;
      const totalUsers = (dataObj.total as number) || 0;
      const activeUsers = (dataObj.active as number) || 0;
      const inactiveUsers = (dataObj.inactive as number) || 0;
      const activationRate = totalUsers > 0 ? ((activeUsers / totalUsers) * 100).toFixed(1) : '0.0';
      
      const userMetricsBoxHeight = 28;
      const userMetricsBoxWidth = 110;
      const userMetricsGap = 8;
      const userMetricsStartX = 50;
      
      // Total box
      doc.rect(userMetricsStartX, userMetricsY, userMetricsBoxWidth, userMetricsBoxHeight)
        .fillColor('#f0f7ff')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0e0f0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Total Users', userMetricsStartX + 5, userMetricsY + 3, { width: userMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(totalUsers), userMetricsStartX + 5, userMetricsY + 14, { width: userMetricsBoxWidth - 10 });
      
      // Active box
      const activeUserX = userMetricsStartX + userMetricsBoxWidth + userMetricsGap;
      doc.rect(activeUserX, userMetricsY, userMetricsBoxWidth, userMetricsBoxHeight)
        .fillColor('#f0fff0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Active', activeUserX + 5, userMetricsY + 3, { width: userMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(activeUsers), activeUserX + 5, userMetricsY + 14, { width: userMetricsBoxWidth - 10 });
      
      // Inactive box
      const inactiveUserX = activeUserX + userMetricsBoxWidth + userMetricsGap;
      doc.rect(inactiveUserX, userMetricsY, userMetricsBoxWidth, userMetricsBoxHeight)
        .fillColor('#fff8f0')
        .fill()
        .fillColor('#000000')
        .strokeColor('#f0e0d0')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Inactive', inactiveUserX + 5, userMetricsY + 3, { width: userMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(String(inactiveUsers), inactiveUserX + 5, userMetricsY + 14, { width: userMetricsBoxWidth - 10 });
      
      // Activation Rate box
      const activationX = inactiveUserX + userMetricsBoxWidth + userMetricsGap;
      doc.rect(activationX, userMetricsY, userMetricsBoxWidth, userMetricsBoxHeight)
        .fillColor('#f0fff8')
        .fill()
        .fillColor('#000000')
        .strokeColor('#d0f0e8')
        .lineWidth(1)
        .stroke();
      doc.fontSize(7).font('Helvetica').fillColor('#666666')
        .text('Activation', activationX + 5, userMetricsY + 3, { width: userMetricsBoxWidth - 10 });
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
        .text(`${activationRate}%`, activationX + 5, userMetricsY + 14, { width: userMetricsBoxWidth - 10 });
      
      doc.y = userMetricsY + userMetricsBoxHeight + 12;
      doc.fillColor('#000000');
      doc.moveDown(0.3);

      if (options?.includeDetailedData && totalUsers > 0) {
        doc.fontSize(10)
          .font('Helvetica-Bold')
          .text('User Statistics')
          .moveDown(0.2);
        doc.fontSize(8)
          .font('Helvetica')
          .fillColor('#333333')
          .text(`Active Rate: ${activationRate}% | Recent: ${(dataObj.recent as number) || 0} (7 days)`, { width: 495 });
        doc.fillColor('#000000');
      }
      break;
    }

    case 'comprehensive': {
      // Comprehensive report includes all analytics sections
      const comprehensiveData = dataObj as {
        location?: Record<string, unknown>;
        agent?: Record<string, unknown>;
        collection?: Record<string, unknown>;
        user?: Record<string, unknown>;
      };

      // Location Analytics Section - Compact
      if (comprehensiveData.location) {
        pdfService.addSectionTitle(doc, 'Location Analytics', 10, 0.2, 'left');
        doc.fontSize(8)
          .font('Helvetica')
          .fillColor('#333333');
        const location = comprehensiveData.location;
        const locY = doc.y;
        doc.text(`Total: ${(location.total as number) || 0}`, 50, locY, { width: 120 })
          .text(`Active: ${(location.active as number) || 0}`, 170, locY, { width: 120 })
          .text(`Usage: ${(location.totalUsage as number) || 0}`, 290, locY, { width: 205 });
        doc.y = locY + 12;
        doc.fillColor('#000000');
        doc.moveDown(0.3);
      }

      // Agent Analytics Section - Compact
      if (comprehensiveData.agent) {
        pdfService.addSectionTitle(doc, 'Agent Analytics', 10, 0.2, 'left');
        doc.fontSize(8)
          .font('Helvetica')
          .fillColor('#333333');
        const agent = comprehensiveData.agent;
        const agents = (agent.agents as Array<Record<string, unknown>>) || [];
        const teamAverages = (agent.teamAverages as { averageCollections?: number; averageRevenue?: number; averageWeight?: number }) || {};
        
        const agentY = doc.y;
        doc.text(`Agents: ${agents.length}`, 50, agentY, { width: 120 });
        if (teamAverages.averageCollections !== undefined) {
          doc.text(`Avg Collections: ${teamAverages.averageCollections.toFixed(1)} | Avg Revenue: ₹${((teamAverages.averageRevenue || 0)).toLocaleString('en-IN')}`, 
            170, agentY, { width: 325 });
        }
        doc.y = agentY + 12;
        doc.fillColor('#000000');
        doc.moveDown(0.3);
      }

      // Collection Analytics Section - Compact
      if (comprehensiveData.collection) {
        pdfService.addSectionTitle(doc, 'Collection Analytics', 10, 0.2, 'left');
        doc.fontSize(8)
          .font('Helvetica')
          .fillColor('#333333');
        const collection = comprehensiveData.collection;
        const collY = doc.y;
        doc.text(`Recycled: ${((collection.totalRecycled as number) || 0).toFixed(2)} kg`, 50, collY, { width: 165 })
          .text(`Pickups: ${collection.totalPickups || 0}`, 215, collY, { width: 280 });
        doc.y = collY + 12;
        doc.fillColor('#000000');
        doc.moveDown(0.3);
      }

      // User Analytics Section - Compact
      if (comprehensiveData.user) {
        pdfService.addSectionTitle(doc, 'User Analytics', 10, 0.2, 'left');
        doc.fontSize(8)
          .font('Helvetica')
          .fillColor('#333333');
        const user = comprehensiveData.user;
        const totalUsers = (user.total as number) || 0;
        const activeUsers = (user.active as number) || 0;
        const inactiveUsers = (user.inactive as number) || 0;
        const activationRate = totalUsers > 0 ? ((activeUsers / totalUsers) * 100).toFixed(1) : '0.0';
        const userY = doc.y;
        doc.text(`Total: ${totalUsers}`, 50, userY, { width: 120 })
          .text(`Active: ${activeUsers}`, 170, userY, { width: 120 })
          .text(`Inactive: ${inactiveUsers}`, 290, userY, { width: 120 })
          .text(`Activation: ${activationRate}%`, 410, userY, { width: 135 });
        doc.y = userY + 12;
        doc.fillColor('#000000');
      }
      break;
    }

    default:
      doc.text(`Unknown report type: ${reportType}`);
      break;
  }

  if (options?.includeCharts) {
    addChartsSection(doc, reportType, dataObj, pdfService);
  }
};

/**
 * Add charts section to PDF based on report type
 */
const addChartsSection = (
  doc: InstanceType<typeof PDFDocument>,
  reportType: ReportType,
  data: Record<string, unknown>,
  pdfService: PdfService
): void => {
  // Check if we need a new page
  pdfService.addPageBreakIfNeeded(doc, 50);
  doc.moveDown(1);
  
  pdfService.addSectionTitle(doc, 'Charts and Visualizations', 10, 0.2, 'left');

  switch (reportType) {
    case 'location':
      addLocationCharts(doc, data);
      break;
    case 'my-analytics':
      addMyAnalyticsCharts(doc, data);
      break;
    case 'agent':
      addAgentCharts(doc, data);
      break;
    case 'collection':
      addCollectionCharts(doc, data);
      break;
    case 'user':
      addUserCharts(doc, data);
      break;
    case 'comprehensive':
      addComprehensiveCharts(doc, data);
      break;
    default:
      doc.fontSize(9)
        .fillColor('#666666')
        .text('Charts and visualizations would be included here. For detailed charts, please refer to the web interface.');
  }
};

/**
 * Add comprehensive analytics charts to PDF
 */
const addComprehensiveCharts = (
  doc: InstanceType<typeof PDFDocument>,
  data: Record<string, unknown>
): void => {
  const comprehensiveData = data as {
    location?: Record<string, unknown>;
    agent?: Record<string, unknown>;
    collection?: Record<string, unknown>;
    user?: Record<string, unknown>;
  };

  // Location charts
  if (comprehensiveData.location) {
    addLocationCharts(doc, comprehensiveData.location);
  }

  // Agent charts
  if (comprehensiveData.agent) {
    addAgentCharts(doc, comprehensiveData.agent);
  }

  // Collection charts
  if (comprehensiveData.collection) {
    addCollectionCharts(doc, comprehensiveData.collection);
  }

  // User charts
  if (comprehensiveData.user) {
    addUserCharts(doc, comprehensiveData.user);
  }
};

/**
 * Add location analytics charts to PDF
 */
const addLocationCharts = (
  doc: InstanceType<typeof PDFDocument>,
  data: Record<string, unknown>
): void => {
  const chartWidth = 480;
  const chartHeight = 200; // More compact
  const chartX = 60;
  const margin = 15;

  // Pie Chart - Usage by Location Type
  const byType = (data.byType as Record<string, number>) || {};
  // Process byType to handle null values
  const processedByType: Record<string, number> = {};
  Object.entries(byType).forEach(([key, value]) => {
    if (value != null && value > 0) {
      // Normalize null/undefined/empty keys
      const normalizedKey = (key === null || key === undefined || key === '' || key === 'null') 
        ? 'Unknown' 
        : key;
      // Sum up if key already exists (in case of multiple null representations)
      processedByType[normalizedKey] = (processedByType[normalizedKey] || 0) + value;
    }
  });
  
  if (Object.keys(processedByType).length > 0) {
    // Check if we need a new page
    if (doc.y + chartHeight + 50 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Usage by Location Type')
      .moveDown(0.2);
    
    const pieY = doc.y;
    drawPieChart(doc, chartX, pieY, chartWidth, chartHeight, processedByType);
    doc.y = pieY + chartHeight + margin;
  }

  // Bar Chart - Top 10 Most Used Locations
  const mostUsed = (data.mostUsed as Array<{ locationName: string; usageCount: number }>) || [];
  if (mostUsed.length > 0) {
    // Check if we need a new page
    if (doc.y + chartHeight + 30 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Top 10 Most Used Locations')
      .moveDown(0.2);
    
    const barY = doc.y;
    drawBarChart(doc, chartX, barY, chartWidth, chartHeight, 
      mostUsed.slice(0, 10).map(loc => ({ label: loc.locationName, value: loc.usageCount }))
    );
    doc.y = barY + chartHeight + margin;
  }

  // Line Chart - Usage Trends Over Time
  const usageTrends = (data.usageTrends as Array<{ date: string; count: number }>) || [];
  if (usageTrends.length > 0) {
    // Check if we need a new page
    if (doc.y + chartHeight + 30 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Usage Trends Over Time')
      .moveDown(0.2);
    
    // Format dates for display - show fewer labels for compactness
    const formattedTrends = usageTrends.map(trend => {
      const date = new Date(trend.date);
      return {
        label: date.toLocaleDateString('en-IN', { month: 'short', day: 'numeric' }),
        value: trend.count || 0,
      };
    });
    
    const lineY = doc.y;
    drawLineChart(doc, chartX, lineY, chartWidth, chartHeight, formattedTrends);
    doc.y = lineY + chartHeight;
  }
};

/**
 * Draw a pie chart using PDFKit
 */
const drawPieChart = (
  doc: InstanceType<typeof PDFDocument>,
  x: number,
  y: number,
  width: number,
  height: number,
  data: Record<string, number>
): void => {
  const centerX = x + width / 2;
  const centerY = y + 80; // Offset from top for title space
  const radius = 60; // Fixed radius for consistency
  const legendStartY = centerY + radius + 20;
  
  // Process and normalize entries, handling null/undefined/empty keys
  const processedData: Record<string, number> = {};
  Object.entries(data).forEach(([key, value]) => {
    if (value != null && value > 0) {
      // Normalize null/undefined/empty keys to 'Unknown'
      const normalizedKey = (key === null || key === undefined || key === '' || key === 'null') 
        ? 'Unknown' 
        : key;
      // Sum up if key already exists (handles multiple null representations)
      processedData[normalizedKey] = (processedData[normalizedKey] || 0) + value;
    }
  });
  
  const entries = Object.entries(processedData);
  const total = entries.reduce((sum, [, value]) => sum + value, 0);
  
  if (total === 0 || entries.length === 0) {
    doc.fontSize(10)
      .fillColor('#666666')
      .text('No data available', centerX - 50, centerY);
    doc.y = y + height;
    return;
  }

  // Colors for pie slices
  const colors = [
    '#3B82F6', // blue
    '#10B981', // green
    '#F59E0B', // amber
    '#EF4444', // red
    '#8B5CF6', // purple
    '#EC4899', // pink
  ];

  // Calculate angles for each slice
  const fullCircle = 2 * Math.PI;
  let currentAngle = -Math.PI / 2; // Start from top (12 o'clock)
  
  // Pre-calculate all angles to ensure they sum to exactly 2π
  const sliceAngles = entries.map(([, value]) => (value / total) * fullCircle);
  const totalCalculated = sliceAngles.reduce((sum, angle) => sum + angle, 0);
  const adjustment = fullCircle - totalCalculated;
  
  // Adjust last slice to ensure exact circle completion
  if (sliceAngles.length > 0 && Math.abs(adjustment) > 0.0001) {
    sliceAngles[sliceAngles.length - 1] += adjustment;
  }
  
  // Draw pie slices using direct coordinate calculation (most reliable)
  entries.forEach((_entry, index) => {
    const sliceAngle = sliceAngles[index];
    const color = colors[index % colors.length];
    const endAngle = currentAngle + sliceAngle;
    
    // Draw pie slice using direct coordinates (no rotation)
    doc.moveTo(centerX, centerY); // Start at center
    
    // Draw line to start of arc
    const startX = centerX + Math.cos(currentAngle) * radius;
    const startY = centerY + Math.sin(currentAngle) * radius;
    doc.lineTo(startX, startY);
    
    // Draw arc using line segments (approximate arc with lines)
    const numSegments = Math.max(10, Math.ceil(sliceAngle * 20)); // More segments for smoother arc
    const angleStep = sliceAngle / numSegments;
    
    for (let i = 1; i <= numSegments; i++) {
      const angle = currentAngle + angleStep * i;
      const x = centerX + Math.cos(angle) * radius;
      const y = centerY + Math.sin(angle) * radius;
      doc.lineTo(x, y);
    }
    
    // Ensure we end exactly at the end angle
    const finalX = centerX + Math.cos(endAngle) * radius;
    const finalY = centerY + Math.sin(endAngle) * radius;
    doc.lineTo(finalX, finalY);
    
    // Close path back to center
    doc.lineTo(centerX, centerY);
    doc.closePath();
    
    // Fill and stroke
    doc.fillColor(color);
    doc.fill();
    doc.strokeColor('#FFFFFF')
      .lineWidth(1)
      .stroke();
    
    // Update angle for next slice
    currentAngle = endAngle;
  });
  
  // Draw outer circle border to ensure visual completeness
  doc.strokeColor('#333333')
    .lineWidth(1.5)
    .circle(centerX, centerY, radius)
    .stroke();
  
  // Draw legend - compact layout
  const legendCols = 3;
  const legendItemWidth = width / legendCols;
  const legendItemHeight = 12;
  
  entries.forEach(([label, value], index) => {
    const col = index % legendCols;
    const row = Math.floor(index / legendCols);
    const legendX = x + col * legendItemWidth;
    const legendY = legendStartY + row * legendItemHeight;
    
    // Color box
    const color = colors[index % colors.length];
    doc.fillColor(color)
      .rect(legendX, legendY, 8, 8)
      .fill();
    
    // Label - handle null/unknown
    const typeLabel = label === 'Unknown' || label === 'null' || !label 
      ? 'Unknown/Not Specified' 
      : getLocationTypeLabel(label);
    const percentage = ((value / total) * 100).toFixed(1);
    doc.fontSize(8)
      .fillColor('#000000')
      .text(`${typeLabel}: ${percentage}%`, legendX + 12, legendY - 1, {
        width: legendItemWidth - 15,
      });
  });
  
  // Update doc.y
  doc.y = legendStartY + Math.ceil(entries.length / legendCols) * legendItemHeight + 5;
};

/**
 * Draw a horizontal bar chart using PDFKit
 */
const drawBarChart = (
  doc: InstanceType<typeof PDFDocument>,
  x: number,
  y: number,
  width: number,
  height: number,
  data: Array<{ label: string; value: number }>
): void => {
  if (data.length === 0) {
    doc.fontSize(10)
      .fillColor('#666666')
      .text('No data available', x, y + height / 2);
    doc.y = y + height;
    return;
  }

  const maxValue = Math.max(...data.map(d => d.value));
  const chartAreaHeight = height - 30; // Space for title
  const barHeight = chartAreaHeight / data.length;
  const chartWidth = width - 130; // Leave space for labels
  const labelWidth = 120;
  const chartStartX = x + labelWidth;
  const chartStartY = y + 25;
  
  data.forEach((item, index) => {
    const barY = chartStartY + index * barHeight;
    const barLength = maxValue > 0 ? (item.value / maxValue) * chartWidth : 0;
    
    // Draw bar with gradient effect (solid color)
    doc.fillColor('#3B82F6')
      .rect(chartStartX, barY, barLength, barHeight - 3)
      .fill();
    
    // Draw value text on bar or next to it
    if (barLength > 40) {
      doc.fontSize(8)
        .fillColor('#FFFFFF')
        .text(item.value.toString(), chartStartX + 3, barY + (barHeight - 3) / 2 - 3);
    } else {
      doc.fontSize(8)
        .fillColor('#000000')
        .text(item.value.toString(), chartStartX + barLength + 5, barY + (barHeight - 3) / 2 - 3);
    }
    
    // Draw label
    const truncatedLabel = item.label.length > 18 ? item.label.substring(0, 15) + '...' : item.label;
    doc.fontSize(8)
      .fillColor('#000000')
      .text(truncatedLabel, x, barY + (barHeight - 3) / 2 - 3, {
        width: labelWidth - 5,
        align: 'right',
      });
  });
  
  // Draw axes
  doc.strokeColor('#333333')
    .lineWidth(0.5)
    .moveTo(chartStartX, chartStartY - 5)
    .lineTo(chartStartX, chartStartY + chartAreaHeight)
    .lineTo(chartStartX + chartWidth, chartStartY + chartAreaHeight)
    .stroke();
  
  // Draw max value label
  if (maxValue > 0) {
    doc.fontSize(7)
      .fillColor('#666666')
      .text(maxValue.toString(), chartStartX + chartWidth - 20, chartStartY - 12, {
        width: 20,
        align: 'right',
      });
  }
  
  // Update doc.y
  doc.y = y + height;
};

/**
 * Draw a line chart using PDFKit
 */
const drawLineChart = (
  doc: InstanceType<typeof PDFDocument>,
  x: number,
  y: number,
  width: number,
  height: number,
  data: Array<{ label: string; value: number }>
): void => {
  if (data.length === 0) {
    doc.fontSize(10)
      .fillColor('#666666')
      .text('No data available', x, y + height / 2);
    doc.y = y + height;
    return;
  }

  const maxValue = Math.max(...data.map(d => d.value));
  const minValue = Math.min(...data.map(d => d.value));
  const valueRange = maxValue - minValue || 1;
  const chartHeight = height - 50; // Leave space for labels
  const chartWidth = width - 70;
  const labelHeight = 40;
  const chartStartX = x + 60;
  const chartStartY = y + labelHeight;
  const pointRadius = 2.5;
  
  // Draw axes
  doc.strokeColor('#333333')
    .lineWidth(0.5)
    .moveTo(chartStartX, chartStartY)
    .lineTo(chartStartX, chartStartY + chartHeight)
    .lineTo(chartStartX + chartWidth, chartStartY + chartHeight)
    .stroke();
  
  // Draw grid lines and Y-axis labels
  const numGridLines = 4;
  for (let i = 0; i <= numGridLines; i++) {
    const gridY = chartStartY + chartHeight - (i / numGridLines) * chartHeight;
    const value = minValue + (i / numGridLines) * valueRange;
    
    // Grid line
    doc.strokeColor('#E5E7EB')
      .lineWidth(0.3)
      .moveTo(chartStartX, gridY)
      .lineTo(chartStartX + chartWidth, gridY)
      .stroke();
    
    // Y-axis label
    doc.fontSize(7)
      .fillColor('#666666')
      .text(Math.round(value).toString(), x, gridY - 4, {
        width: 55,
        align: 'right',
      });
  }
  
  // Draw data points and line
  if (data.length > 1) {
    const stepX = chartWidth / (data.length - 1);
    const points: Array<{ x: number; y: number }> = [];
    
    data.forEach((item, index) => {
      const pointX = chartStartX + index * stepX;
      const normalizedValue = (item.value - minValue) / valueRange;
      const pointY = chartStartY + chartHeight - normalizedValue * chartHeight;
      
      points.push({ x: pointX, y: pointY });
    });
    
    // Draw filled area under line
    doc.save();
    doc.moveTo(points[0].x, chartStartY + chartHeight);
    points.forEach(point => doc.lineTo(point.x, point.y));
    doc.lineTo(points[points.length - 1].x, chartStartY + chartHeight);
    doc.closePath();
    doc.fillColor('#3B82F6')
      .opacity(0.1)
      .fill();
    doc.restore();
    
    // Draw line
    doc.strokeColor('#3B82F6')
      .lineWidth(2);
    points.forEach((point, index) => {
      if (index === 0) {
        doc.moveTo(point.x, point.y);
      } else {
        doc.lineTo(point.x, point.y);
      }
    });
    doc.stroke();
    
    // Draw points
    points.forEach(point => {
      doc.fillColor('#3B82F6')
        .circle(point.x, point.y, pointRadius)
        .fill();
      // White center for better visibility
      doc.fillColor('#FFFFFF')
        .circle(point.x, point.y, pointRadius * 0.5)
        .fill();
    });
    
    // Draw X-axis labels (every nth label to avoid crowding)
    const maxLabels = 8;
    const labelInterval = Math.max(1, Math.floor(data.length / maxLabels));
    data.forEach((item, index) => {
      if (index % labelInterval === 0 || index === data.length - 1) {
        const labelX = chartStartX + index * stepX;
        doc.fontSize(6)
          .fillColor('#666666')
          .text(item.label, labelX - 15, chartStartY + chartHeight + 3, {
            width: 30,
            align: 'center',
          });
      }
    });
  } else if (data.length === 1) {
    // Single data point
    const pointX = chartStartX + chartWidth / 2;
    const normalizedValue = (data[0].value - minValue) / valueRange;
    const pointY = chartStartY + chartHeight - normalizedValue * chartHeight;
    
    doc.fillColor('#3B82F6')
      .circle(pointX, pointY, pointRadius)
      .fill();
  }
  
  // Update doc.y
  doc.y = y + height;
};

/**
 * Add my analytics charts to PDF
 */
const addMyAnalyticsCharts = (
  doc: InstanceType<typeof PDFDocument>,
  data: Record<string, unknown>
): void => {
  const chartWidth = 480;
  const chartHeight = 200;
  const chartX = 60;
  const margin = 15;

  // Material Type Pie Chart
  const byMaterialType = (data.byMaterialType as Array<{ materialType: string; count: number; totalWeight: number }>) || [];
  if (byMaterialType.length > 0) {
    if (doc.y + chartHeight + 50 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Collections by Material Type')
      .moveDown(0.2);
    
    const pieY = doc.y;
    const materialTypeData: Record<string, number> = {};
    byMaterialType.forEach(item => {
      const key = item.materialType || 'Unknown';
      materialTypeData[key] = item.count || 0;
    });
    
    drawPieChart(doc, chartX, pieY, chartWidth, chartHeight, materialTypeData);
    doc.y = pieY + chartHeight + margin;
  }

  // Weight by Material Type Bar Chart
  if (byMaterialType.length > 0) {
    if (doc.y + chartHeight + 30 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Weight by Material Type')
      .moveDown(0.2);
    
    const barY = doc.y;
    const barData = byMaterialType.map(item => ({
      label: getMaterialTypeLabel(item.materialType || 'Unknown'),
      value: item.totalWeight || 0,
    }));
    
    drawBarChart(doc, chartX, barY, chartWidth, chartHeight, barData);
    doc.y = barY + chartHeight;
  }
};

/**
 * Add agent analytics charts to PDF
 */
const addAgentCharts = (
  doc: InstanceType<typeof PDFDocument>,
  data: Record<string, unknown>
): void => {
  const chartWidth = 480;
  const chartHeight = 200;
  const chartX = 60;
  const margin = 15;

  // Leaderboard Bar Chart - By Collections
  const leaderboard = (data.leaderboard as { 
    byCollections?: Array<{ agentName: string; value: number }>;
    byRevenue?: Array<{ agentName: string; value: number }>;
  }) || {};
  const byCollections = leaderboard.byCollections || [];
  
  if (byCollections.length > 0) {
    if (doc.y + chartHeight + 50 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Top Agents by Collections')
      .moveDown(0.2);
    
    const barY = doc.y;
    const barData = byCollections.slice(0, 10).map((item: { agentName: string; value: number }) => ({
      label: item.agentName || 'Unknown',
      value: item.value || 0,
    }));
    
    drawBarChart(doc, chartX, barY, chartWidth, chartHeight, barData);
    doc.y = barY + chartHeight + margin;
  }

  // Revenue Leaderboard
  const byRevenue = leaderboard.byRevenue || [];
  if (byRevenue.length > 0) {
    if (doc.y + chartHeight + 30 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Top Agents by Revenue')
      .moveDown(0.2);
    
    const barY2 = doc.y;
    const barData2 = byRevenue.slice(0, 10).map((item: { agentName: string; value: number }) => ({
      label: item.agentName || 'Unknown',
      value: item.value || 0,
    }));
    
    drawBarChart(doc, chartX, barY2, chartWidth, chartHeight, barData2);
    doc.y = barY2 + chartHeight;
  }
};

/**
 * Add collection analytics charts to PDF
 */
const addCollectionCharts = (
  doc: InstanceType<typeof PDFDocument>,
  data: Record<string, unknown>
): void => {
  const chartWidth = 480;
  const chartHeight = 200;
  const chartX = 60;
  const margin = 15;

  // Material Type Pie Chart
  const byMaterialType = (data.byMaterialType as Array<{ materialType: string; count: number; totalWeight: number }>) || [];
  if (byMaterialType.length > 0) {
    if (doc.y + chartHeight + 50 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Collections by Material Type')
      .moveDown(0.2);
    
    const pieY = doc.y;
    const materialTypeData: Record<string, number> = {};
    byMaterialType.forEach(item => {
      const key = item.materialType || 'Unknown';
      materialTypeData[key] = item.count || 0;
    });
    
    drawPieChart(doc, chartX, pieY, chartWidth, chartHeight, materialTypeData);
    doc.y = pieY + chartHeight + margin;
  }

  // Weight by Material Type Bar Chart
  if (byMaterialType.length > 0) {
    if (doc.y + chartHeight + 30 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('Weight by Material Type')
      .moveDown(0.2);
    
    const barY = doc.y;
    const barData = byMaterialType.map(item => ({
      label: getMaterialTypeLabel(item.materialType || 'Unknown'),
      value: item.totalWeight || 0,
    }));
    
    drawBarChart(doc, chartX, barY, chartWidth, chartHeight, barData);
    doc.y = barY + chartHeight;
  }
};

/**
 * Add user analytics charts to PDF
 */
const addUserCharts = (
  doc: InstanceType<typeof PDFDocument>,
  data: Record<string, unknown>
): void => {
  const chartWidth = 480;
  const chartHeight = 200;
  const chartX = 60;
  const margin = 15;

  // User Status Pie Chart
  const activeUsers = (data.active as number) || 0;
  const inactiveUsers = (data.inactive as number) || 0;
  
  if (activeUsers > 0 || inactiveUsers > 0) {
    if (doc.y + chartHeight + 50 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('User Status Distribution')
      .moveDown(0.2);
    
    const pieY = doc.y;
    const userStatusData: Record<string, number> = {
      'Active': activeUsers,
      'Inactive': inactiveUsers,
    };
    
    drawPieChart(doc, chartX, pieY, chartWidth, chartHeight, userStatusData);
    doc.y = pieY + chartHeight + margin;
  }

  // User Status Bar Chart
  if (activeUsers > 0 || inactiveUsers > 0) {
    if (doc.y + chartHeight + 30 > 750) {
      doc.addPage();
    }
    
    doc.fontSize(10)
      .font('Helvetica-Bold')
      .text('User Status Overview')
      .moveDown(0.2);
    
    const barY = doc.y;
    const barData = [
      { label: 'Total', value: (data.total as number) || 0 },
      { label: 'Active', value: activeUsers },
      { label: 'Inactive', value: inactiveUsers },
    ];
    
    drawBarChart(doc, chartX, barY, chartWidth, chartHeight, barData);
    doc.y = barY + chartHeight;
  }
};

const convertAnalyticsDataToCSV = (reportType: ReportType, data: unknown): Array<Record<string, string | number>> => {
  const rows: Array<Record<string, string | number>> = [];

  if (!data || typeof data !== 'object') {
    return rows;
  }

  const dataObj = data as Record<string, unknown>;

  switch (reportType) {
    case 'my-analytics': {
      const myOverview = (dataObj.overview as Record<string, unknown>) || {};
      rows.push({
        'Metric': 'Total Collections',
        'Value': (myOverview.totalCollections as number) || 0,
      });
      rows.push({
        'Metric': 'Total Receipts',
        'Value': (myOverview.totalReceipts as number) || 0,
      });
      rows.push({
        'Metric': 'Total Weight (kg)',
        'Value': ((myOverview.totalWeight as number) || 0).toFixed(2),
      });
      rows.push({
        'Metric': 'Total Amount (₹)',
        'Value': (myOverview.totalAmount as number) || 0,
      });

      // Add material type breakdown - Compact
      const byMaterialType = (dataObj.byMaterialType as Array<{ materialType: string; count: number; totalWeight: number }>) || [];
      if (byMaterialType.length > 0) {
        rows.push({ 'Metric': '', 'Value': '' }); // Separator
        rows.push({ 'Metric': 'Material Type Breakdown', 'Value': '' });
        byMaterialType.forEach(item => {
          const materialLabel = getMaterialTypeLabel(item.materialType || 'Unknown');
          rows.push({
            'Metric': materialLabel,
            'Count': item.count || 0,
            'Weight (kg)': ((item.totalWeight as number) || 0).toFixed(2),
          });
        });
      }

      // Add location type breakdown - Compact
      const byLocationType = (dataObj.byLocationType as Array<{ locationType: string; count: number }>) || [];
      if (byLocationType.length > 0) {
        rows.push({ 'Metric': '', 'Value': '' }); // Separator
        rows.push({ 'Metric': 'Location Type Breakdown', 'Value': '' });
        byLocationType.forEach(item => {
          const locationLabel = getLocationTypeLabel(item.locationType || 'Unknown');
          rows.push({
            'Metric': locationLabel,
            'Value': item.count || 0,
          });
        });
      }
      break;
    }

    case 'location': {
      rows.push({
        'Metric': 'Total Locations',
        'Value': (dataObj.total as number) || 0,
      });
      rows.push({
        'Metric': 'Active Locations',
        'Value': (dataObj.active as number) || 0,
      });
      rows.push({
        'Metric': 'Inactive Locations',
        'Value': (dataObj.inactive as number) || 0,
      });
      rows.push({
        'Metric': 'Total Usage',
        'Value': (dataObj.totalUsage as number) || 0,
      });
      rows.push({
        'Metric': 'Average Usage',
        'Value': ((dataObj.averageUsage as number) || 0).toFixed(2),
      });

      // Location Type Breakdown - Handle null values
      const byType = (dataObj.byType as Record<string, number>) || {};
      const typeEntries = Object.entries(byType)
        .filter(([, count]) => count != null && count > 0)
        .map(([type, count]) => {
          const normalizedType = (type === null || type === undefined || type === '' || type === 'null') 
            ? 'Unknown' 
            : type;
          return [normalizedType, count] as [string, number];
        });
      
      if (typeEntries.length > 0) {
        rows.push({ 'Metric': '', 'Value': '' }); // Separator
        rows.push({ 'Metric': 'Location Type Breakdown', 'Value': '' });
        typeEntries.forEach(([type, count]) => {
          const typeLabel = type === 'Unknown' 
            ? 'Unknown/Not Specified' 
            : getLocationTypeLabel(type);
          rows.push({
            'Metric': typeLabel,
            'Value': count,
          });
        });
      }

      // Most Used Locations
      const mostUsed = (dataObj.mostUsed as Array<{ locationName: string; usageCount: number }>) || [];
      if (mostUsed.length > 0) {
        rows.push({ 'Metric': '', 'Value': '' }); // Separator
        rows.push({ 'Metric': 'Top 10 Most Used Locations', 'Value': '' });
        mostUsed.slice(0, 10).forEach((loc, index) => {
          rows.push({
            'Metric': `${index + 1}. ${loc.locationName}`,
            'Value': loc.usageCount || 0,
          });
        });
      }

      // Usage Trends Summary
      const usageTrends = (dataObj.usageTrends as Array<{ date: string; count: number }>) || [];
      if (usageTrends.length > 0) {
        rows.push({ 'Metric': '', 'Value': '' }); // Separator
        rows.push({ 'Metric': 'Usage Trends', 'Value': '' });
        const totalCollections = usageTrends.reduce((sum, trend) => sum + (trend.count || 0), 0);
        const avgPerDay = usageTrends.length > 0 ? totalCollections / usageTrends.length : 0;
        rows.push({
          'Metric': 'Total Collections in Period',
          'Value': totalCollections,
        });
        rows.push({
          'Metric': 'Average Collections per Day',
          'Value': avgPerDay.toFixed(1),
        });
        // Add daily breakdown if not too many entries
        if (usageTrends.length <= 30) {
          usageTrends.forEach(trend => {
            const date = new Date(trend.date).toLocaleDateString('en-IN');
            rows.push({
              'Metric': `Collections on ${date}`,
              'Value': trend.count || 0,
            });
          });
        }
      }

      // By City Breakdown
      const byCity = (dataObj.byCity as Array<{ city: string; count: number }>) || [];
      if (byCity.length > 0) {
        rows.push({ 'Metric': '', 'Value': '' }); // Separator
        rows.push({ 'Metric': 'Locations by City', 'Value': '' });
        byCity.forEach(item => {
          rows.push({
            'Metric': item.city,
            'Value': item.count,
          });
        });
      }
      break;
    }

    case 'agent': {
      const agents = (dataObj.agents as Array<Record<string, unknown>>) || [];
      const teamAverages = (dataObj.teamAverages as { averageCollections?: number; averageRevenue?: number; averageWeight?: number; averageCollectionsPerDay?: number; averageCollectionValue?: number }) || {};
      
      // Summary row
      const totalCollections = agents.reduce((sum, agent) => sum + ((agent.totalCollections as number) || 0), 0);
      const totalRevenue = agents.reduce((sum, agent) => sum + ((agent.totalRevenue as number) || 0), 0);
      rows.push({
        'Metric': 'Total Agents',
        'Value': agents.length,
      });
      rows.push({
        'Metric': 'Total Collections',
        'Value': totalCollections,
      });
      rows.push({
        'Metric': 'Total Revenue (₹)',
        'Value': totalRevenue,
      });
      
      if (agents.length === 0) {
        rows.push({
          'Agent Name': 'No agents found',
          'Collections': 0,
          'Revenue (₹)': 0,
          'Weight (kg)': '0.00',
          'Collections/Day': '0.00',
          'Avg Value': '0.00',
        });
      } else {
        rows.push({ 'Metric': '', 'Value': '' }); // Separator
        rows.push({ 'Metric': 'Agent Details', 'Value': '' });
        
        agents.forEach(agent => {
          rows.push({
            'Agent Name': (agent.agentName as string) || 'Unknown',
            'Collections': (agent.totalCollections as number) || 0,
            'Revenue (₹)': (agent.totalRevenue as number) || 0,
            'Weight (kg)': ((agent.totalWeight as number) || 0).toFixed(2),
            'Collections/Day': ((agent.collectionsPerDay as number) || 0).toFixed(2),
            'Avg Value': agent.averageCollectionValue ? ((agent.averageCollectionValue as number).toFixed(2)) : '0.00',
          });
        });
        
        // Add team averages row if available
        if (teamAverages.averageCollections !== undefined) {
          rows.push({ 'Agent Name': '', 'Collections': '', 'Revenue (₹)': '', 'Weight (kg)': '', 'Collections/Day': '', 'Avg Value': '' }); // Separator
          rows.push({
            'Agent Name': 'Team Average',
            'Collections': teamAverages.averageCollections.toFixed(1),
            'Revenue (₹)': (teamAverages.averageRevenue || 0).toFixed(2),
            'Weight (kg)': (teamAverages.averageWeight || 0).toFixed(2),
            'Collections/Day': (teamAverages.averageCollectionsPerDay || 0).toFixed(2),
            'Avg Value': (teamAverages.averageCollectionValue || 0).toFixed(2),
          });
        }
      }
      break;
    }

    case 'collection': {
      rows.push({
        'Metric': 'Total Recycled (kg)',
        'Value': ((dataObj.totalRecycled as number) || 0).toFixed(2),
      });
      rows.push({
        'Metric': 'Total Pickups',
        'Value': (dataObj.totalPickups as number) || 0,
      });
      const totalPickups = (dataObj.totalPickups as number) || 0;
      const totalRecycled = (dataObj.totalRecycled as number) || 0;
      if (totalPickups > 0) {
        rows.push({
          'Metric': 'Average per Pickup (kg)',
          'Value': (totalRecycled / totalPickups).toFixed(2),
        });
      }
      
      const collectionByMaterialType = (dataObj.byMaterialType as Array<{ materialType: string; count: number; totalWeight: number }>) || [];
      if (collectionByMaterialType.length > 0) {
        rows.push({ 'Metric': '', 'Value': '' }); // Separator
        rows.push({ 'Metric': 'Material Type Breakdown', 'Value': '' });
        collectionByMaterialType.forEach(item => {
          const materialLabel = getMaterialTypeLabel(item.materialType || 'Unknown');
          rows.push({
            'Material Type': materialLabel,
            'Count': item.count || 0,
            'Weight (kg)': ((item.totalWeight as number) || 0).toFixed(2),
          });
        });
      }
      break;
    }

    case 'user': {
      rows.push({
        'Metric': 'Total Users',
        'Value': (dataObj.total as number) || 0,
      });
      rows.push({
        'Metric': 'Active Users',
        'Value': (dataObj.active as number) || 0,
      });
      rows.push({
        'Metric': 'Inactive Users',
        'Value': (dataObj.inactive as number) || 0,
      });
      break;
    }

    case 'comprehensive': {
      // Comprehensive report includes all analytics data
      // Use consistent column structure: Section, Category, Metric, Value
      const comprehensiveData = dataObj as {
        location?: Record<string, unknown>;
        agent?: Record<string, unknown>;
        collection?: Record<string, unknown>;
        user?: Record<string, unknown>;
      };

      // Location Analytics
      if (comprehensiveData.location) {
        rows.push({ 'Section': 'Location Analytics', 'Category': 'Summary', 'Metric': 'Total Locations', 'Value': ((comprehensiveData.location.total as number) || 0).toString() });
        rows.push({ 'Section': 'Location Analytics', 'Category': 'Summary', 'Metric': 'Active Locations', 'Value': ((comprehensiveData.location.active as number) || 0).toString() });
        rows.push({ 'Section': 'Location Analytics', 'Category': 'Summary', 'Metric': 'Total Usage', 'Value': ((comprehensiveData.location.totalUsage as number) || 0).toString() });
      }

      // Agent Analytics
      if (comprehensiveData.agent) {
        const agent = comprehensiveData.agent;
        const agents = (agent.agents as Array<Record<string, unknown>>) || [];
        const teamAverages = (agent.teamAverages as { averageCollections?: number; averageRevenue?: number; averageWeight?: number; averageCollectionsPerDay?: number; averageCollectionValue?: number }) || {};
        
        if (agents.length === 0) {
          rows.push({ 'Section': 'Agent Analytics', 'Category': 'Summary', 'Metric': 'Total Agents', 'Value': '0' });
        } else {
          rows.push({ 'Section': 'Agent Analytics', 'Category': 'Summary', 'Metric': 'Total Agents', 'Value': agents.length.toString() });
          
          agents.forEach(agentItem => {
            rows.push({
              'Section': 'Agent Analytics',
              'Category': 'Agent Details',
              'Metric': (agentItem.agentName as string) || 'Unknown',
              'Value': `${(agentItem.totalCollections as number) || 0} collections, ₹${((agentItem.totalRevenue as number) || 0).toLocaleString('en-IN')}, ${((agentItem.totalWeight as number) || 0).toFixed(2)} kg`,
            });
          });
          
          if (teamAverages.averageCollections !== undefined) {
            rows.push({
              'Section': 'Agent Analytics',
              'Category': 'Team Averages',
              'Metric': 'Average Collections',
              'Value': teamAverages.averageCollections.toFixed(1),
            });
            rows.push({
              'Section': 'Agent Analytics',
              'Category': 'Team Averages',
              'Metric': 'Average Revenue',
              'Value': `₹${((teamAverages.averageRevenue || 0)).toLocaleString('en-IN')}`,
            });
            rows.push({
              'Section': 'Agent Analytics',
              'Category': 'Team Averages',
              'Metric': 'Average Weight',
              'Value': `${((teamAverages.averageWeight || 0)).toFixed(2)} kg`,
            });
          }
        }
      }

      // Collection Analytics
      if (comprehensiveData.collection) {
        const collection = comprehensiveData.collection;
        rows.push({
          'Section': 'Collection Analytics',
          'Category': 'Summary',
          'Metric': 'Total Recycled',
          'Value': `${((collection.totalRecycled as number) || 0).toFixed(2)} kg`,
        });
        rows.push({
          'Section': 'Collection Analytics',
          'Category': 'Summary',
          'Metric': 'Total Pickups',
          'Value': ((collection.totalPickups as number) || 0).toString(),
        });
        const collectionByMaterialType = (collection.byMaterialType as Array<{ materialType: string; count: number; totalWeight: number }>) || [];
        if (collectionByMaterialType.length > 0) {
          collectionByMaterialType.forEach(item => {
            rows.push({
              'Section': 'Collection Analytics',
              'Category': 'Material Breakdown',
              'Metric': item.materialType,
              'Value': `${item.count} collections, ${item.totalWeight.toFixed(2)} kg`,
            });
          });
        }
      }

      // User Analytics
      if (comprehensiveData.user) {
        const user = comprehensiveData.user;
        rows.push({
          'Section': 'User Analytics',
          'Category': 'Summary',
          'Metric': 'Total Users',
          'Value': ((user.total as number) || 0).toString(),
        });
        rows.push({
          'Section': 'User Analytics',
          'Category': 'Summary',
          'Metric': 'Active Users',
          'Value': ((user.active as number) || 0).toString(),
        });
        rows.push({
          'Section': 'User Analytics',
          'Category': 'Summary',
          'Metric': 'Inactive Users',
          'Value': ((user.inactive as number) || 0).toString(),
        });
      }
      break;
    }

    default:
      // Unknown report type - return empty rows
      logger.warn(`Unknown report type in convertAnalyticsDataToCSV: ${reportType}`);
      break;
  }

  return rows;
};

export const analyticsReportService = {
  generateReport,
  generatePDFReport,
  generateCSVReport,
  getReportSuggestions,
};
