apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: web-public-secrets
  labels:
    app: web-public
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: web-public-secrets
    creationPolicy: Owner
  data:
  - secretKey: api-base-url
    remoteRef:
      key: everbloom/production/web-public
      property: api-base-url
  - secretKey: socket-url
    remoteRef:
      key: everbloom/production/web-public
      property: socket-url
