apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - external-secret.yaml

commonLabels:
  app: web-public
  component: frontend

images:
  - name: web-public
    newName: 361116840324.dkr.ecr.ap-south-2.amazonaws.com/everbloom/web-public
    newTag: latest
