apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
spec:
  data:
  - secretKey: root-username
    remoteRef:
      key: everbloom/development/mongodb
      property: root-username
  - secretKey: root-password
    remoteRef:
      key: everbloom/development/mongodb
      property: root-password
  - secretKey: username
    remoteRef:
      key: everbloom/development/mongodb
      property: username
  - secretKey: password
    remoteRef:
      key: everbloom/development/mongodb
      property: password
