apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - secret-store.yaml
  - cluster-issuer.yaml
  - ../../../apps/mongodb/base
  - ./api-core
  - ./web-admin
  - ./web-public
