apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/everbloomsolutions/everbloom.git
    targetRevision: develop
    path: deploy/environments/development/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
