apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-admin-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/everbloomsolutions/everbloom.git
    targetRevision: main
    path: deploy/environments/production/web-admin
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
