apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-admin-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/everbloom/everbloom.git
    targetRevision: develop
    path: deploy/environments/development/web-admin
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
