apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../../apps/web-public/base

replicas:
  - name: web-public
    count: 2

patchesStrategicMerge:
  - patch.yaml

images:
  - name: web-public
    newTag: staging
